### ISSUE TITLE
Not Showing 'Magnet' Menu XC6.2

### ISSUE THREAD

**Issue by SteveDCronin** [magnetsystems/r2m-plugin-ios#4]
Followed the 3 step script
Here's the result:
Last login: Tue Mar 17 11:09:48 on console
Steve-iMac:~ steve$ ls -laf /Users/steve/Library/Application\ Support/Developer/Shared/Xcode/
total 16
drwxr-xr-x  5 steve  staff   170 Mar 17 11:05 .
drwxr-xr-x  4 steve  staff   136 Mar 17 10:54 ..
-rw-r--r--@ 1 steve  staff  6148 Mar 17 11:05 .DS_Store
drwxr-xr-x  4 steve  staff   136 Mar 17 11:05 Plug-ins
drwxr-xr-x  3 steve  staff   102 Jan 18  2014 Screenshots
Steve-iMac:~ steve$ ls -laf /Users/steve/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/
total 16
drwxr-xr-x  4 steve  staff   136 Mar 17 11:05 .
drwxr-xr-x  5 steve  staff   170 Mar 17 11:05 ..
-rw-r--r--@ 1 steve  staff  6148 Mar 17 11:05 .DS_Store
drwxr-xr-x  3 steve  staff   102 Oct 30 15:47 Magnet.xcplugin
Steve-iMac:~ steve$ 

I open a xc6.2 project with an iOS target.
Can I ask what would prevent this from being used by OS X also?

In any case, I don't see a 'Magnet' menu.
How can I use Xcode to help you?
I don't see a UI to plug-ins?..?

![menubar_and_boomthang-iphone_xcodeproj_and_steve_ _bash_ _105x24](https://cloud.githubusercontent.com/assets/1017615/6692159/ffbcede6-cc98-11e4-8548-d1ea8f715273.png)

**Comment by priteshshah1983** [comment]
I'm working on it. Will have a fix shortly!

**Comment by priteshshah1983** [comment]
@SteveDCronin Can you try v1.1.2? https://github.com/magnetsystems/r2m-plugin-ios/releases/tag/v1.1.2

Please note that the menu item has been renamed to R2M now.

**Comment by SteveDCronin** [comment]
That did it

Thank- you for the startlingly fast response!!

Why can’t I use this tool on OS X?

Steve

**Comment by priteshshah1983** [comment]
Actually, we designed it to work for iOS, but it should work on OS X as well. I will update the podspec so that it works for OS X soon. You can create a local podspec and include OS X in the meantime and try it out.

Let me know how it goes.

**Comment by priteshshah1983** [comment]
v1.1.4 or Rest2Mobile now supports OS X.
